version: 3.7
services:
  rnotify-scraper:
    image: localhost/username/rnotify-app:v0.0.1
    container_name: scraper-container
    # It is a CronJob in Kubernetes
    command: 
      - /bin/sh
      - -c
      - |
        while true
        do
          python scraper.py
          sleep 3600
        done
    environment:
      - RNOTIFY_CONFIG_FILE=/etc/rnotify/config.toml
    volumes:
      - ./config.toml:/etc/rnotify/config.toml
    depends_on:
      - rnotify-notifier
    restart: on-failure

  rnotify-notifier:
    image: localhost/username/rnotify-app:v0.0.1
    container_name: notifier-container
    command: 
      - /bin/sh
      - -c
      - python notifier.py
    environment:
      - RNOTIFY_CONFIG_FILE=/etc/rnotify/config.toml
    volumes:
      - ./config.toml:/etc/rnotify/config.toml
      - ./templates/notification.html.j2:/etc/rnotify/templates/notification.html.j2
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: docker.io/bitnami/redis:7.2.5
    volumes:
      - redis:/bitnami/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
volumes:
  redis: null
