broker_uri="redis://localhost:6379"
backend_uri="redis://localhost:6379"

github_repos=["grafana/grafana", "derailed/k9s"]
github_api_url="https://api.github.com/repos/"
github_api_token=""

gitlab_repos=["AuroraOSS/AuroraStore"]
gitlab_api_url="https://gitlab.com/api/v4/projects/"
gitlab_api_token=""

notification_template="/home/dell/Projects/rnotify/templates/notification.html.j2"
recipient="recipient@email.com"
smtp_username="username@email.com"
smtp_password="password"
smtp_server="smtp.email.com"
smtp_port=465
