apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "rnotify.fullname" . }}
  namespace: {{ include "rnotify.namespace" . }}
  labels:
    {{- include "rnotify.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "rnotify.selectorLabels" . | nindent 6 }}
  schedule: "{{ .Values.rnotify.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "rnotify.selectorLabels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- include "rnotify.pod" . | nindent 10 }}