apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rnotify.fullname" . }}
  namespace: {{ include "rnotify.namespace" . }}
  labels:
    {{- include "rnotify.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "rnotify.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.rnotify.replicas }}
  template:
    metadata:
      labels:
        {{- include "rnotify.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "rnotify.pod" . | nindent 6 }}
