namespaceOverride: ""
fullnameOverride: ""
nameOverride: ""

imagePullSecrets: []

rnotify:
  name: rnotify

  annotations: {}
  labels: {}

  podAnnotations: {}
  podLabels: {}
  
  replicas: 1
  schedule: "* * * * *"
  
  imagePullPolicy: IfNotPresent
  image:
    registry: docker.io
    repository: faresherhar/rnotify-app
    tag: "sss"

  command:
    - /bin/sh
    - -c
    - date; echo Hello from the Kubernetes cluster

  env: {}

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001

  podSecurityContext:
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false

  extraInitContainers: []
  extraContainers: []

  extraVolumeMounts: []
  extraVolumes: []

  tolerations: []
  nodeSelector: {}
  affinity: {}

  config: |
    broker_uri="redis://localhost:6379"
    backend_uri="redis://localhost:6379"

    github_repos=["grafana/grafana", "derailed/k9s"]
    github_api_url="https://api.github.com/repos/"
    github_api_token=""

    gitlab_repos=["AuroraOSS/AuroraStore"]
    gitlab_api_url="https://gitlab.com/api/v4/projects/"
    gitlab_api_token=""

    notification_template="/home/rnotify/templates/notification.html.j2"
    recipient="recipient@example-email.com"
    smtp_username="username@example-email.com"
    smtp_password="password"
    smtp_server="smtp.example-email.com"
    smtp_port=465
